version: '3.1'

services:

  mysql:
    image: mysql:5.7
    container_name: app-mysql
    volumes:
      - ./dev/mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: app
    ports:
      - '3307:3306'

  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile.App
    ports:
      - "8080:8080"
      - "8070:8070"
    links:
      - mysql:mysql
    volumes:
      - ${PWD}:/go/src/github.com/patrickascher/gofer-skeleton
    depends_on:
      - mysql
